version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: local-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka
    ports:
      - "9092:9092"   # Accessible from your host machine
      - "9094:9094"   # External listener
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "kraft-cluster-1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: local-kafka-ui
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: Local-Dev-Cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  postgres:
    image: postgres:15-alpine
    container_name: meet_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: meet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432" # Mapped to 5433 on the host to avoid port conflict
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  meet-ms:
    build: ./meet_ms
    container_name: meet_ms_app
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meet_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      # If you need to point to your google-credentials.json inside the container
      # GOOGLE_APPLICATION_CREDENTIALS: /app/src/main/resources/google-credentials.json
    depends_on:
      - postgres
      - kafka

  notification-ms:
    build: ./notification_ms
    container_name: notification_ms_app
    ports:
      - "8082:8082"
    environment:
      AUTH_MS_URL: http://auth-ms:8083
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MAIL_USERNAME: voskanyannelli03@gmail.com
      MAIL_PASSWORD: ddwckexjvrzgusvl
    depends_on:
      - kafka
      - auth-ms

  auth-ms:
    build: ./auth_ms
    container_name: auth_ms_app
    ports:
      - "8083:8083"
    environment:
      APPLICATION_SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - auth-postgres
      - kafka

  gateway-ms:
    build: ./gateway_ms
    container_name: gateway_ms_app
    ports:
      - "8000:8000" # Expose the "Front Door" to your computer
    environment:
      APPLICATION_SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      AUTH_MS_URL: http://auth-ms:8083
      MEET_MS_URL: http://meet-ms:8080
    depends_on:
      - auth-ms
      - meet-ms

  # ==========================================
  # OBSERVABILITY STACK
  # ==========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mounts the local file
    depends_on:
      - meet-ms
      - notification-ms

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data:
    driver: local
  auth_postgres_data:
    driver: local