server:
  port: 8082

AUTH_MS_URL: http://localhost:8083

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: voskanyannelli03@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true