apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/lib/kafka/data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
      containers:
        - name: kafka
          image: apache/kafka:3.7.0
          imagePullPolicy: IfNotPresent
          env:
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK-X86sw"
          command:
            - sh
            - -euc
            - |
              /opt/kafka/bin/kafka-storage.sh format \
                -t "$CLUSTER_ID" \
                -c /tmp/server.properties \
                --ignore-formatted

              exec /opt/kafka/bin/kafka-server-start.sh /tmp/server.properties
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9093
              name: controller
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 300
            periodSeconds: 30
            failureThreshold: 5
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
            - name: kafka-config
              mountPath: /tmp/server.properties
              subPath: server.properties.template
      volumes:
        - name: kafka-config
          configMap:
            name: kafka-config
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi