apiVersion: v1
kind: ConfigMap
metadata:
  name: meetbase-config
data:
  SPRING_PROFILES_ACTIVE: "stand"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  AUTH_MS_URL: "http://auth-ms:8083"
  MEET_MS_URL: "http://meet-ms-service:8080"
  DB_USERNAME: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: meetbase-secrets
type: Opaque
stringData:
  DB_PASSWORD: "root"
  APPLICATION_SECURITY_JWT_SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  MAIL_USERNAME: "voskanyannelli03@gmail.com"
  MAIL_PASSWORD: "ddwckexjvrzgusvl"