apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-ms-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-ms
  template:
    metadata:
      labels:
        app: notification-ms
    spec:
      containers:
        - name: notification-ms
          image: localhost/notification-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: meetbase-config
            - secretRef:
                name: meetbase-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: notification-ms
spec:
  selector:
    app: notification-ms
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082