server:
  port: 8000
application:
  security:
    jwt:
      # THIS MUST MATCH AUTH_MS EXACTLY!
      secret-key: 
spring:
  application:
    name: gateway_ms
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: false
            maxAge: 3600

      routes:
        # --- API Routes ---
        - id: auth-service
          uri: http://auth-ms:8083
          predicates:
            - Path=/api/v1/users/**, /users/**
          filters:
            - AuthenticationFilter

        - id: meet-service
          uri: http://meet-ms:8080
          predicates:
            - Path=/meets/**
          filters:
            - AuthenticationFilter

        # --- Swagger Doc Routes ---
        - id: auth-service-docs
          uri: http://auth-ms:8083
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: meet-service-docs
          uri: http://meet-ms:8080
          predicates:
            - Path=/v3/api-docs/meet
          filters:
            - RewritePath=/v3/api-docs/meet, /v3/api-docs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: Meet Service
        url: /v3/api-docs/meet
  api-docs:
    enabled: true