server:
  port: 8000
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_MS_URL:http://auth-ms:8083}
          predicates:
            - Path=/api/v1/users/**, /users/**
          filters:
            - AuthenticationFilter

        - id: meet-service
          uri: ${MEET_MS_URL:http://meet-ms:8080}
          predicates:
            - Path=/meets/**
          filters:
            - AuthenticationFilter

        - id: auth-service-docs
          uri: ${AUTH_MS_URL:http://auth-ms:8083}
          predicates:
            - Path=/v3/api-docs/auth
          filters:
            - RewritePath=/v3/api-docs/auth, /v3/api-docs

        - id: meet-service-docs
          uri: ${MEET_MS_URL:http://meet-ms:8080}
          predicates:
            - Path=/v3/api-docs/meet
          filters:
            - RewritePath=/v3/api-docs/meet, /v3/api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /v3/api-docs/auth
      - name: Meet Service
        url: /v3/api-docs/meet
  api-docs:
    enabled: true